/**
 * Author: Yzrel Jade B. Eborde
 */

import { useRef } from "react";
import { Printer } from "lucide-react";
import type { LoiDocumentResponse } from "../api/types";

interface LoiDocumentPreviewProps {
  document: LoiDocumentResponse;
  applicationId?: string;
  showToolbar?: boolean;
}

export function LoiDocumentPreview({
  document: doc,
  applicationId,
  showToolbar = true,
}: LoiDocumentPreviewProps) {
  const printRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="border border-gray-200 rounded-xl overflow-hidden">
      {showToolbar && (
        <div className="flex items-center justify-between px-5 py-3 bg-gray-50 border-b border-gray-200 print:hidden">
          <p className="text-sm font-bold text-gray-700">Letter of Intent — Document Preview</p>
          <div className="flex items-center gap-2">
            {!doc.aiGenerated && (
              <span className="text-xs text-amber-700 bg-amber-50 border border-amber-100 px-2 py-1 rounded-lg">
                Template draft (AI unavailable)
              </span>
            )}
            {doc.provincialOfficeDefaulted && (
              <span className="text-xs text-amber-700 bg-amber-50 border border-amber-100 px-2 py-1 rounded-lg">
                PSTO defaulted to regional
              </span>
            )}
            <button
              type="button"
              onClick={handlePrint}
              className="flex items-center gap-1.5 text-xs text-blue-600 bg-blue-50 border border-blue-100 px-3 py-1.5 rounded-lg hover:bg-blue-100 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" /> Print / Download
            </button>
          </div>
        </div>
      )}

      <div
        ref={printRef}
        id="loi-document-print"
        className="p-8 sm:p-10 space-y-5 text-sm text-gray-800 leading-relaxed font-serif bg-white max-h-[520px] overflow-y-auto print:max-h-none print:overflow-visible print:p-12"
      >
        {/* Enterprise letterhead */}
        <div className="space-y-0.5">
          <p className="font-black text-base uppercase tracking-wide">{doc.letterhead.enterpriseName}</p>
          <p>{doc.letterhead.address}</p>
          {doc.letterhead.email && <p>Email: {doc.letterhead.email}</p>}
          {doc.letterhead.mobile && <p>Mobile: {doc.letterhead.mobile}</p>}
          <p className="pt-3">{doc.letterhead.date}</p>
        </div>

        <div className="h-4" />

        {/* Regional addressee */}
        <div className="space-y-0.5">
          {doc.regionalAddressee.lines.map((line, i) => (
            <p key={`regional-${i}`} className={i === 0 ? "font-semibold" : ""}>
              {line}
            </p>
          ))}
        </div>

        <div className="h-4" />

        {/* THRU provincial office */}
        <div className="space-y-0.5">
          {doc.thruAddressee.lines.map((line, i) => (
            <p key={`thru-${i}`} className={i === 0 ? "font-semibold" : ""}>
              {line}
            </p>
          ))}
        </div>

        <div className="h-4" />

        <p>{doc.salutation}</p>

        {doc.bodyParagraphs.map((paragraph, i) => (
          <p key={`body-${i}`} className="text-justify">
            {paragraph}
          </p>
        ))}

        <p>{doc.closing}</p>

        <div className="mt-8 space-y-1">
          <p className="font-black text-gray-800 border-b border-gray-500 inline-block pr-20 italic pb-1">
            {doc.signature.typedName}
          </p>
          <p className="font-semibold text-gray-800">{doc.signature.printedName}</p>
          <p className="text-gray-600">{doc.signature.designation}</p>
          <p className="text-gray-600">{doc.signature.enterpriseName}</p>
          <p className="text-gray-400 text-xs mt-1">Date Signed: {doc.signature.dateSigned}</p>
        </div>

        {(applicationId || doc.generatedAt) && (
          <div className="border-t border-gray-200 pt-4 text-xs text-gray-400 space-y-0.5 print:mt-12">
            {applicationId && <p>Application ID: {applicationId}</p>}
            <p>Generated by DOST aiSETUP Portal · {new Date(doc.generatedAt).toLocaleString("en-PH")}</p>
          </div>
        )}
      </div>
    </div>
  );
}
